image: dotnet:2.1-sdk

before_script:

test-build:
  script:
    - dotnet build
test-publish:
  script:
    - dotnet publish --output /srv/dotnet/tephraSystemEditor

reload-service:
  script:
    - sudo systemctl restart tephraSystemEditor.service