before_script:

test-build:
  script:
    - dotnet build
test-publish:
  script:
    - dotnet publish --output /srv/dotnet/tephraSystemEditor

reload-service:
  script:
    - sudo systemctl reload dotnet.service